### ISSUE TITLE
Go Live no longer works 

### ISSUE THREAD

**Issue by Rocketboy235** [nelsonjchen/op-replay-clipper#30]
When trying to start the web server by clicking on Go Live in the bottom right corner, the following is displayed when it tries to load the page showing the directory of the live server.

![image](https://github.com/nelsonjchen/op-replay-clipper/assets/29405055/afe2aa52-5428-4282-a7a8-1c57b031fee6)

**Comment by nelsonjchen** [comment]
Pretty sure this is a codespaces bug at the moment:

https://github.com/orgs/community/discussions?discussions_q=is%3Aopen+port+forwarding

Unfortunately, I'm not sure where GitHub is tracking it.

**Comment by nelsonjchen** [comment]
As an example, I can't even get it to forward `python -m http.server`, one of the simplest servers out there.

**Comment by nelsonjchen** [comment]
I've chosen to simply deprecate Codespaces and use replicate.com to host the clipper where this issue is no longer applicable.
