### ISSUE TITLE
Prediction failed error

### ISSUE THREAD

**Issue by AbeerBPi** [nelsonjchen/op-replay-clipper#71]
![image](https://github.com/nelsonjchen/op-replay-clipper/assets/49898638/ae5f511c-ad51-4ce5-adac-19a24da6afc9)

https://replicate.com/p/iwj53djbckuptahtrhlex73yla

**Comment by nelsonjchen** [comment]
Probably some weird issue with repeated cancellations and cancellations
cleanup not working. I do have other issues about that. Still leaving this
issue open though.

**Comment by nelsonjchen** [comment]
Did some remediation since this issue was made. Please reopen if this happens again.
