### ISSUE TITLE
Clipper is broken

### ISSUE THREAD

**Issue by nelsonjchen** [nelsonjchen/op-replay-clipper#73]
Segment start times missing?

**Comment by nelsonjchen** [comment]
Downloader is having the issue

**Comment by ngk0** [comment]
I saw the segment start times issue as well.   No matter what the inputs were, even the example threw the error.

**Comment by nelsonjchen** [comment]
Yeah the backend API has changed. Need to teach downloader module new
endpoints.

**Comment by nelsonjchen** [comment]
https://replicate.com/p/x4cmvrkj4srg80cenmwvkqcz44

Hmm, for some reason, it's unable to generate a X11 config so the OP UI can run. Might be a replicate.com regression.

At least ffmpeg UI-less clipping can run now. Progress is progress.

**Comment by nelsonjchen** [comment]
Worked around that X11 config issue by generating the config by hand with past values and hardcoding. I think it's probable that the `nvidia-xconfig` command no longer really works.
