### ISSUE TITLE
Issue with download button

### ISSUE THREAD

**Issue by Rocketboy235** [nelsonjchen/op-replay-clipper#77]
Never had much luck with this. I think it worked in the past for me but also sometimes, just does not work (i.e. stuck on Preparing). Not 100% sure why but anyway, not a huge deal since the workaround is to just click on the vertical ellipsis button in the lower right corner of the video and download via that. 

![image](https://github.com/nelsonjchen/op-replay-clipper/assets/29405055/b0a65da9-331c-4f54-b96d-987e0ce0b79c)

**Comment by nelsonjchen** [comment]
I think it's a quirk of replicate.com. maybe website permissions.

**Comment by nelsonjchen** [comment]
Like, check if your setup somehow limits localStorage or something. Their implementation smells of using that.
