### ISSUE TITLE
Better handle and do trial customer limits for DigitalOcean by default with `--slow-cpu` and 4 vCPUs by default for DigitalOcean

### ISSUE THREAD

**Issue by nelsonjchen** [nelsonjchen/op-replay-clipper#9]
* New DigitalOcean customers are limited to 4 vCPUs
* They will get assigned dirty/tainted IP addresses
* The web server stuff may be confusing and can be accidentally quit. Maybe make it start in the background persistently instead of foreground on demand with DO-specific instructions.

Many thanks to DrWumbo#4031 for walking through their different POV as a DigitalOcean trial customer.

**Comment by nelsonjchen** [comment]
Left DO in favor of Codespaces

**Comment by JamesL6** [comment]
This is awesome! Love the fast changes
